<p><strong>CONTRATO DE LOCA&Ccedil;&Atilde;O COM PRAZO DETERMINADO DE {!! $meses !!} MESES</strong></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">Fazem entre si, RONILDA LORENTZ, brasileira, viuva, portadora do</span> <span style="font-weight: 400;">RG nMG-5.512.420 expedida pela SSP/RS e inscrito no CPF sob o n 708.156.826-20, residente e domiciliado na Rua Jos&eacute; Luiz de Deus n42, Bairro Parque S&atilde;o Pedro Venda Nova, Belo Horizonte, MG, doravante denominado LOCADOR e {!! $contrato->clientes->nome !!}, brasileiro, casado, contador, portador do RG n {!! $contrato->clientes->rg !!} e inscrito no CPF sob o n{!! $contrato->clientes->cpf !!}, doravante denominado LOCAT&Aacute;RIO, o presente CONTRATO DE LOCA&Ccedil;&Atilde;O pelas cl&aacute;usulas que seguem:</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA PRIMEIRA</strong><span style="font-weight: 400;">: O LOCADOR d&aacute; em loca&ccedil;&atilde;o o im&oacute;vel de sua propriedade situado na Rua Jos&eacute; Luiz de Deus n&nbsp;{!! $contrato->aluguels->numeroAluguel !!}, Bairro Parque S&atilde;o Pedro Venda Nova, Venda Nova;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA SEGUNDA</strong><span style="font-weight: 400;">: O prazo da loca&ccedil;&atilde;o &eacute; de {!! $meses !!} meses, iniciando no dia { Carbon\Carbon::parse($contrato->dataInicioContrato)->format('d/m') } de { Carbon\Carbon::parse($contrato->dataInicioContrato)->format('Y') } e terminando no dia { Carbon\Carbon::parse($contrato->dataFimContrato)->format('d/m') } de { Carbon\Carbon::parse($contrato->dataFimContrato)->format('Y') };</span></p>
<ul>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 1. Terminado o prazo inicialmente convencionado e n&atilde;o havendo qualquer manifesta&ccedil;&atilde;o das partes a loca&ccedil;&atilde;o ser&aacute; prorrogada por tempo indeterminado, podendo ser denunciada por qualquer das duas partes a qualquer tempo, com aviso pr&eacute;vio de 30 (trinta) dias a serem utilizados para a desocupa&ccedil;&atilde;o do im&oacute;vel;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 2. Caso o LOCAT&Aacute;RIO n&atilde;o conceda o aviso pr&eacute;vio quando da desocupa&ccedil;&atilde;o do im&oacute;vel no caso acima especificado, ficar&aacute; obrigado a pagar, a t&iacute;tulo de multa, o valor de um m&ecirc;s de aluguel;</span></li>
</ul>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA TERCEIRA</strong><span style="font-weight: 400;">: O aluguel mensal convencionado &eacute; de R$ &nbsp;{!! $contrato->aluguels->valorAluguelMensal !!} a serem pagos pelo LOCAT&Aacute;RIO at&eacute; o dia 05 do m&ecirc;s subseq&uuml;ente ao vencido a ser pago diretamente ao LOCADOR, mediante recibo ou</span> <span style="font-weight: 400;">atrav&eacute;s de dep&oacute;sito na conta do LOCADOR do Banco Banco Bradesco Ag&ecirc;ncia: 3804 C/C: 11710-2 ou Boleto Gerado, servindo o recibo de dep&oacute;sito como comprovante de pagamento do aluguel e encargos decorrentes da loca&ccedil;&atilde;o; </span></p>
<ul>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 1Ser&aacute; de responsabilidade do LOCAT&Aacute;RIO os pagamentos de IPTU, condom&iacute;nio, &aacute;gua, luz, seguro contra inc&ecirc;ndio e todas as demais despesas ordin&aacute;rias referentes &agrave; conserva&ccedil;&atilde;o do im&oacute;vel legalmente permitidas por lei e eventuais taxas futuras que vierem a ser criadas pelo Poder P&uacute;blico futuramente;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 2O pagamento do fundo de reserva do condom&iacute;nio &eacute; de responsabilidade do LOCADOR e caso seja pago pelo LOCAT&Aacute;RIO ser&aacute; reembolsado semestralmente pelo valor constante do documento de pagamento comprovadamente efetuado;</span></li>
</ul>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA QUARTA</strong><span style="font-weight: 400;">: O aluguel ser&aacute; reajustado automaticamente na periodicidade m&iacute;nima determinada pela legisla&ccedil;&atilde;o vigente pelo &Iacute;ndice Geral de Pre&ccedil;os de Mercado fornecido pela Funda&ccedil;&atilde;o Get&uacute;lio Vargas (IGP-M) ou na falta deste pelo &Iacute;ndice de Pre&ccedil;os do Consumidor calculado pela Funda&ccedil;&atilde;o Instituto de Pesquisas Econ&ocirc;micas (IPC-FIPE) ou ainda na aus&ecirc;ncias destes pelo &Iacute;ndices de Pre&ccedil;os ao Consumidor calculado pelo Centro de Estudos e Pesquisas Econ&ocirc;micas da Faculdade de Ci&ecirc;ncias Econ&ocirc;micas da UFRGS (IPE-POA-IEPE) ou o &iacute;ndice que vier a substitu&iacute;-los. </span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA QUINTA</strong><span style="font-weight: 400;">: Caso n&atilde;o haja o pagamento at&eacute; o prazo convencionado no contrato (cl&aacute;usula 3</span><span style="font-weight: 400;">a</span><span style="font-weight: 400;">) incidir&aacute; multa de 10% sobre o valor do aluguel mais juros de mora de 1% &nbsp;e corre&ccedil;&atilde;o monet&aacute;ria apurados no per&iacute;odo;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">Par&aacute;grafo &uacute;nico: caber&aacute; ao LOCAT&Aacute;RIO as penalidades decorrentes dos atrasos nos pagamentos do condom&iacute;nio, luz, &aacute;gua, taxas, etc.;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA SEXTA</strong><span style="font-weight: 400;">: O im&oacute;vel locado destina-se, exclusivamente para fins residenciais, sendo-lhe vedada outra destina&ccedil;&atilde;o, transfer&ecirc;ncia ou sub loca&ccedil;&atilde;o, total ou parcial sem o consentimento expresso do LOCADOR;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA S&Eacute;TIMA</strong><span style="font-weight: 400;">: O LOCAT&Aacute;RIO declara ter recebido o im&oacute;vel em perfeitas condi&ccedil;&otilde;es de habitabilidade e reparado em toda sua extens&atilde;o;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">Par&aacute;grafo &uacute;nico: faz parte integrante deste contrato termo de vistoria do im&oacute;vel locado com as condi&ccedil;&otilde;es gerais do im&oacute;vel locado;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA OITAVA</strong><span style="font-weight: 400;">: O LOCAT&Aacute;RIO obriga-se a manter o im&oacute;vel locado sempre limpo e restitu&iacute;-lo, finda a loca&ccedil;&atilde;o, nas mesmas e perfeitas condi&ccedil;&otilde;es de habitabilidade recebidas, de acordo com o termo de vistoria, correndo exclusivamente por sua conta, todos os reparos tendentes &agrave; conserva&ccedil;&atilde;o do im&oacute;vel, das suas depend&ecirc;ncias, instala&ccedil;&otilde;es e utens&iacute;lios nele existentes, inclusive os consertos e reparos que se fizerem necess&aacute;rios na rede de &aacute;gua e esgoto, bem como as multas que der causa, por inobserv&acirc;ncia de quaisquer leis, decretos e regulamentos;</span></p>
<ul>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 1Caso o im&oacute;vel, suas depend&ecirc;ncias e utens&iacute;lios nele existentes, n&atilde;o forem restitu&iacute;dos nas mesmas condi&ccedil;&otilde;es estipuladas nesta cl&aacute;usula e na cl&aacute;usula s&eacute;tima, o aluguel e seus acess&oacute;rios continuar&atilde;o a correr, at&eacute; que o LOCAT&Aacute;RIO cumpra todas as exig&ecirc;ncias do LOCADOR, com base na vistoria referida;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 2O LOCAT&Aacute;RIO ou o fiador que receber as chaves do im&oacute;vel para mandar proceder aos reparos que forem exigidos, ter&aacute; o prazo de 15 (quinze) dias para execut&aacute;-los. O n&atilde;o cumprimento das obriga&ccedil;&otilde;es no prazo fixado, dar&aacute; ao LOCADOR o direito de entrar na posse do im&oacute;vel, procedendo-se, ent&atilde;o, na forma determinada do &sect; 3infra;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 3Caso os reparos exigidos pelo LOCADOR n&atilde;o sejam executados dentro de 15 (quinze) dias contados da entrega das chaves, o LOCAT&Aacute;RIO ou seu fiador e principal pagador obrigam-se a depositar em m&atilde;os do LOCADOR ou onde este indicar, o valor correspondente ao or&ccedil;amento apresentado pelo vistoriador. N&atilde;o sendo executados os reparos, nem sendo depositado o valor do or&ccedil;amento apresentado, na forma e no prazo acima fixado, poder&aacute; o LOCADOR, se assim desejar, mandar executar os reparos para o que fica, desde j&aacute;, autorizado pelo LOCAT&Aacute;RIO e pelo fiador e principal pagador, os quais reconhecem como id&ocirc;neo o or&ccedil;amento apresentado e de cujo valor total se consideram devedores, autorizando, por conseguinte, a sua cobran&ccedil;a mediante a&ccedil;&atilde;o de execu&ccedil;&atilde;o, na forma do inciso IV do artigo 585 do C&oacute;digo de Processo Civil;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 4O disposto no par&aacute;grafo 3supra aplicar-se-&aacute;, tamb&eacute;m, no que diz respeito aos reparos ou consertos que tiverem que ser executados no curso da loca&ccedil;&atilde;o;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 5Quando da desocupa&ccedil;&atilde;o e entrega do im&oacute;vel, o LOCAT&Aacute;RIO dever&aacute; apresentar os comprovantes de que est&atilde;o completamente quitadas todas as contas de energia el&eacute;trica, &aacute;gua, imposto predial, condom&iacute;nio e taxas que vierem a ser criadas pela prefeitura que sejam de responsabilidade legal ou contratual do LOCAT&Aacute;RIO, correndo a loca&ccedil;&atilde;o at&eacute; o momento em que forem apresentados os comprovantes mencionados;</span></li>
</ul>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA NONA</strong><span style="font-weight: 400;">: Quaisquer obras ou benfeitorias dependem do consentimento expresso e escrito do LOCADOR e n&atilde;o dar&atilde;o direito a indeniza&ccedil;&atilde;o ou reten&ccedil;&atilde;o e, finda a loca&ccedil;&atilde;o, poder&aacute; o LOCADOR exigir-lhe retirada.</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA</strong><span style="font-weight: 400;">: &Eacute; vedado ao LOCAT&Aacute;RIO a coloca&ccedil;&atilde;o de placas, bandeiras, cartazes, pain&eacute;is, luminosos, antenas, etc., nas paredes externas do im&oacute;vel locado;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">Par&aacute;grafo &uacute;nico: embora autorizado, o LOCAT&Aacute;RIO responde pelos danos que, nessa hip&oacute;tese, foram causados ao im&oacute;vel;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA PRIMEIRA</strong><span style="font-weight: 400;">: O LOCAT&Aacute;RIO obriga-se a respeitar, al&eacute;m das posturas municipais, e das de sa&uacute;de, os regulamentos e conven&ccedil;&otilde;es do edif&iacute;cio, ficando respons&aacute;vel pelas multas a que der causa;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA SEGUNDA</strong><span style="font-weight: 400;">: O LOCADOR poder&aacute; dar como rescindido o presente contrato de loca&ccedil;&atilde;o de pleno direito, independentemente de qualquer interpela&ccedil;&atilde;o judicial, sem que assista ao LOCAT&Aacute;RIO direito a qualquer indeniza&ccedil;&atilde;o ou reclama&ccedil;&atilde;o, a exemplo: a) Em caso do n&atilde;o pagamento pontual do aluguel e encargos ou a falta do exato cumprimento de qualquer das obriga&ccedil;&otilde;es; b) Em caso de sinistro ou desapropria&ccedil;&atilde;o; c) A n&atilde;o substitui&ccedil;&atilde;o do fiador quando o aceito falecer, tornar-se insolvente civilmente ou vender o im&oacute;vel oferecido como garantia; d) Dar destina&ccedil;&atilde;o diversa do que consta no contrato; e) Sub locar o im&oacute;vel sem autoriza&ccedil;&atilde;o expressa do LOCADOR; f) Infringir qualquer das cl&aacute;usulas do presente contrato;</span></p>
<ul>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">1Uma vez tendo o LOCAT&Aacute;RIO dado motivo &agrave; rescis&atilde;o do contrato de loca&ccedil;&atilde;o pagar&aacute; este uma multa de 3 vezes o valor do locat&iacute;cio ajustado atualizado, independentemente das san&ccedil;&otilde;es anteriormente previstas;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 2Incorrer&aacute; na mesma multa do par&aacute;grafo acima se o LOCAT&Aacute;RIO decidir rescindir o contrato dentro do prazo m&iacute;nimo convencionado no contrato de loca&ccedil;&atilde;o;</span></li>
</ul>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA TERCEIRA</strong><span style="font-weight: 400;">: O LOCADOR n&atilde;o se responsabiliza por eventuais danos sofridos pelo LOCAT&Aacute;RIO em caso de acidentes ocasionados por caso fortuito ou de for&ccedil;a maior;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA QUARTA</strong><span style="font-weight: 400;">: N&atilde;o poder&aacute; o LOCAT&Aacute;RIO escusar-se ao pagamento de quaisquer diferen&ccedil;as de aluguel, impostos, taxas, despesas de condom&iacute;nios ou outro &ocirc;nus a que estiver obrigado nos termos da lei e do presente instrumento, sob a alega&ccedil;&atilde;o de que o pagamento n&atilde;o lhe foi exigido na &eacute;poca fixada neste contrato de loca&ccedil;&atilde;o;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA QUINTA</strong><span style="font-weight: 400;">: Quaisquer toler&acirc;ncias ou concess&otilde;es do LOCADOR n&atilde;o constituir&atilde;o precedente invoc&aacute;vel e n&atilde;o ter&atilde;o a virtude de alterar as obriga&ccedil;&otilde;es que lhe s&atilde;o impostas neste instrumento;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA SEXTA</strong><span style="font-weight: 400;">: Caso ocorra o atraso no pagamento do aluguel e o mesmo seja enviado para cobran&ccedil;a em escrit&oacute;rio de advocacia o LOCAT&Aacute;RIO ficar&aacute; sujeita ao pagamento dos honor&aacute;rios do profissional na base de 20% do valor do d&eacute;bito atualizado, independentemente das multas e comina&ccedil;&otilde;es legais;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA S&Eacute;TIMA</strong><span style="font-weight: 400;">: Os prazos e as obriga&ccedil;&otilde;es do LOCAT&Aacute;RIO se vencer&atilde;o independentemente de interpela&ccedil;&atilde;o, notifica&ccedil;&atilde;o ou aviso, judicial ou extrajudicial;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA OITAVA</strong><span style="font-weight: 400;">: O vencimento do aluguel impago conferir&aacute; o direito do LOCADOR em ingressar com a&ccedil;&atilde;o de despejo para desocupa&ccedil;&atilde;o do im&oacute;vel, sendo que a n&atilde;o propositura desta a&ccedil;&atilde;o logo ap&oacute;s o vencimento n&atilde;o caracterizar&aacute; a morat&oacute;ria prevista no inciso I do artigo 838 do C&oacute;digo Civil Brasileiro;</span></p>
<p><span style="font-weight: 400;">@if($contrato->clientes->possuiFiador == 'SIM')</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA D&Eacute;CIMA NONA</strong><span style="font-weight: 400;">: Como fiador e principal pagador de todas as obriga&ccedil;&otilde;es que incumbem ao LOCAT&Aacute;RIO, por for&ccedil;a de lei e do presente contrato e at&eacute; a desocupa&ccedil;&atilde;o do im&oacute;vel e sua entrega nas condi&ccedil;&otilde;es previstas nas cl&aacute;usulas s&eacute;tima e oitava, bem como pelas altera&ccedil;&otilde;es do aluguel e acess&oacute;rios, que ocorrerem no curso da loca&ccedil;&atilde;o, em virtude de aplica&ccedil;&atilde;o de &iacute;ndices autorizados por lei, em virtude de cl&aacute;usulas contratuais ou de reajustamentos autorizados por escrito pelo LOCAT&Aacute;RIO obrigam-se o Sr. {!! $contrato->clientes->nomeFiador!!}, brasileiro(a), residente e domiciliado na {!! $contrato->clientes->enderecoFiador!!}, portador do RG n{!! $contrato->clientes->rgFiador!!}, CPF n{!! $contrato->clientes->cpfFiador!!} que declara o fiador, sob as penas da lei estar o referido bem livre de quaisquer &ocirc;nus ou obriga&ccedil;&otilde;es de qualquer esp&eacute;cie;</span></p>
<p><span style="font-weight: 400;">@endif</span></p>
<ul>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 1O fiador </span><strong>expressamente renuncia o direito do artigo 827, do C&oacute;digo Civil Brasileiro</strong><span style="font-weight: 400;">, tornando-se, portanto, solid&aacute;rio e principal devedor de todos os d&eacute;bitos decorrentes do presente contrato de loca&ccedil;&atilde;o;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 2O fiador igualmente </span><strong>renuncia os direitos decorrentes do artigo 835 do C&oacute;digo Civil Brasileiro</strong><span style="font-weight: 400;">;</span></li>
    <li><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> 3O fiador est&aacute; de pleno acordo que, durante o curso da loca&ccedil;&atilde;o, LOCADOR e LOCAT&Aacute;RIO ajustem novos valores e obriga&ccedil;&otilde;es locat&iacute;cias, dispensando a necessidade de aposi&ccedil;&atilde;o de suas assinaturas;</span></li>
</ul>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA VIG&Eacute;SIMA</strong><span style="font-weight: 400;">: Em caso de morte do fiador fica o LOCAT&Aacute;RIO obrigado a apresentar outro fiador id&ocirc;neo com id&ecirc;nticas garantias, no prazo de 15 dias, sob pena de rescis&atilde;o do presente contrato de loca&ccedil;&atilde;o;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA VIG&Eacute;SIMA PRIMEIRA</strong><span style="font-weight: 400;">: Em caso de morte do LOCAT&Aacute;RIO, o fiador continua respons&aacute;vel como principal pagador at&eacute; a desocupa&ccedil;&atilde;o do im&oacute;vel e sua entrega nas mesma condi&ccedil;&otilde;es que foram estabelecidas nas cl&aacute;usulas s&eacute;tima e oitavas.</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA VIG&Eacute;SIMA SEGUNDA</strong><span style="font-weight: 400;">: O contrato &eacute; regido pela lei n8.245/91 e C&oacute;digo Civil Brasileiro, no que couber, devendo os problemas que surgirem serem resolvidos baseados nos dois diplomas legais;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <strong>CL&Aacute;USULA VIG&Eacute;SIMA TERCEIRA</strong><span style="font-weight: 400;">: Os contratantes elegem o Foro Central de Porto Alegre, por mais privilegiado que possa ser qualquer outro, para dirimir quaisquer d&uacute;vidas surgidas do presente contrato;</span></p>
<p><span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> E por estarem justos e contratados as partes firmam o presente contrato em duas vias de igual conte&uacute;do e teor para que surjam seus legais e jur&iacute;dicos efeitos na presen&ccedil;a de duas testemunhas, que igualmente assinam.</span></p>
<p><span style="font-weight: 400;">Belo Horizonte, &nbsp;de &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {!! Carbon\Carbon::today()->format('d/m')   !!} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;de  {!! Carbon\Carbon::today()->format('Y')   !!} </span></p>
<p><span style="font-weight: 400;">__________________________ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">__________________________</span></p>
<p><span style="font-weight: 400;">RONILDA LORENTZ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{!! $contrato->clientes->nome!!}</span></p>
<p><span style="font-weight: 400;">@if($contrato->clientes->possuiFiador == 'SIM')</span></p>
<p><span style="font-weight: 400;">__________________________ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;">{!! $contrato->clientes->nome!!} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;"> @endif</span></p>
<p><span style="font-weight: 400;">Testemunha &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span style="font-weight: 400;">Testemunha</span></p>